# Generated by Django 4.1.1 on 2022-11-28 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0007_alter_comment_comment_body'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'verbose_name_plural': 'Posts'},
        ),
    ]
